# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
service: speedl

image: m324/speedl

servers:
  web:
    hosts:
      - <%= ENV.fetch('KAMAL_SERVER_IP') %>

registry:
  server: <%= ENV.fetch('KAMAL_REGISTRY') || 'not-defined' %>
  username: AWS

  password: <%= ENV.fetch('KAMAL_REGISTRY_PASSWORD') || 'not-defined' %>

ssh:
  user: ubuntu

proxy:
  app_port: 8080
  healthcheck:
    path: /up
    interval: 2
    timeout: 2

builder:
  arch: amd64
